# Generated by Django 5.1.2 on 2024-11-09 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('frequency', models.CharField(choices=[('hourly', 'Каждый час'), ('every_3_hours', 'Каждые 3 часа'), ('every_12_hours', 'Каждые 12 часов'), ('daily_9am', 'Ежедневно в 9:00'), ('weekly', 'Еженедельно')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
