# Generated by Django 5.1.2 on 2024-11-10 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_notificationsetting_last_sent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationsetting',
            name='frequency',
            field=models.CharField(choices=[('every_minute', 'Каждую минуту'), ('hourly', 'Каждый час'), ('every_3_hours', 'Каждые 3 часа'), ('every_12_hours', 'Каждые 12 часов'), ('daily_9am', 'Ежедневно в 9:00'), ('weekly', 'Еженедельно')], max_length=20),
        ),
    ]
