services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: postgres_weather
      POSTGRES_USER: postgres_weather_user
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}  # Используем переменные окружения
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"


  celery-worker:
    build: .
    command: celery -A weat worker --loglevel=info --pool=solo
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis

  celery_beat:
    build: .
    command: celery -A weat beat --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
