# Generated by Django 5.1.2 on 2024-11-04 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WeatherData',
        ),
    ]
